services:
  - type: web
    name: my-app
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server/index.js
    plan: starter
    autoDeploy: true
    region: singapore
    disk:
      name: data
      mountPath: /data
      sizeGB: 5
